# This workflow should be placed in the web-app repository
# Location: .github/workflows/deploy.yaml

name: Build and Deploy to ArgoCD

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'package*.json'
      - '.github/workflows/deploy.yaml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image-tag: ${{ steps.meta.outputs.tags }}
      image-digest: ${{ steps.build.outputs.digest }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

      - name: Generate image tag for k8s
        id: image-tag
        run: |
          # Extract the SHA-based tag (e.g., main-abc1234)
          FULL_TAG="${{ steps.meta.outputs.tags }}"
          SHA_TAG=$(echo "$FULL_TAG" | grep -o 'main-[a-f0-9]\{7\}' | head -1)
          if [ -z "$SHA_TAG" ]; then
            SHA_TAG="main-${GITHUB_SHA::7}"
          fi
          echo "tag=$SHA_TAG" >> $GITHUB_OUTPUT
          echo "full-image=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$SHA_TAG" >> $GITHUB_OUTPUT

  update-manifest:
    name: Update Kubernetes Manifest
    runs-on: ubuntu-latest
    needs: build-and-push
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update image tag in manifest
        run: |
          # Update the image tag in the deployment manifest
          # Assumes your deployment is at k8s/base/deployment.yaml

          NEW_IMAGE="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.build-and-push.outputs.image-tag }}"

          # Using sed to update the image
          sed -i "s|image: ghcr.io/${{ github.repository }}:.*|image: $NEW_IMAGE|g" k8s/base/deployment.yaml

          # Alternative: Use yq for more robust YAML editing
          # yq eval '.spec.template.spec.containers[0].image = "'$NEW_IMAGE'"' -i k8s/base/deployment.yaml

      - name: Commit and push manifest changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add k8s/base/deployment.yaml

          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Update image to ${{ needs.build-and-push.outputs.image-tag }}

          Automated deployment from commit ${{ github.sha }}

          Image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.build-and-push.outputs.image-tag }}
          Digest: ${{ needs.build-and-push.outputs.image-digest }}"

          git push

  notify-argocd:
    name: Trigger ArgoCD Sync (Optional)
    runs-on: ubuntu-latest
    needs: update-manifest
    if: github.event_name == 'push'
    steps:
      - name: Wait for ArgoCD to detect changes
        run: |
          echo "Manifest updated. ArgoCD will auto-sync within ~3 minutes."
          echo "To force immediate sync, use ArgoCD UI or CLI."

      # Optional: Use ArgoCD API to force sync immediately
      # Requires ARGOCD_TOKEN secret
      # - name: Trigger ArgoCD Sync
      #   run: |
      #     curl -X POST \
      #       -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}" \
      #       https://argocd.yourdomain.com/api/v1/applications/charno-web/sync

  deployment-summary:
    name: Deployment Summary
    runs-on: ubuntu-latest
    needs: [build-and-push, update-manifest]
    if: always()
    steps:
      - name: Summary
        run: |
          echo "## Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Image:** ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.build-and-push.outputs.image-tag }}" >> $GITHUB_STEP_SUMMARY
          echo "**Digest:** ${{ needs.build-and-push.outputs.image-digest }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Status:** Manifest updated, ArgoCD will sync automatically" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Next Steps" >> $GITHUB_STEP_SUMMARY
          echo "- ArgoCD will detect the change within 3 minutes" >> $GITHUB_STEP_SUMMARY
          echo "- Check ArgoCD UI for sync status" >> $GITHUB_STEP_SUMMARY
          echo "- Monitor deployment: \`kubectl get pods -n charno-web\`" >> $GITHUB_STEP_SUMMARY
