# Simplified workflow for web-app repository
# This builds, pushes, and updates k8s manifests for ArgoCD to deploy

name: Deploy with ArgoCD

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        id: build
        run: |
          # Generate tag from git SHA
          TAG="main-${GITHUB_SHA::7}"
          IMAGE="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$TAG"

          # Build and push
          docker build -t $IMAGE .
          docker push $IMAGE

          # Also tag as latest
          docker tag $IMAGE ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

          echo "image=$IMAGE" >> $GITHUB_OUTPUT
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Update Kubernetes Manifest
        run: |
          # Update image in deployment
          sed -i "s|image: ghcr.io/${{ github.repository }}:.*|image: ${{ steps.build.outputs.image }}|g" k8s/base/deployment.yaml

      - name: Commit Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s/base/deployment.yaml
          git diff --staged --quiet || git commit -m "Deploy ${{ steps.build.outputs.tag }}"
          git push

      - name: Summary
        run: |
          echo "✅ Deployed: ${{ steps.build.outputs.image }}" >> $GITHUB_STEP_SUMMARY
          echo "ArgoCD will sync within 3 minutes" >> $GITHUB_STEP_SUMMARY
