---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth
  namespace: database
spec:
  encryptedData:
    password: AgANvvg4AdZOWVBVIQyFskY/4ETnh6veQzS0XJhTiZ/pM+HqJjlrlGBBGr5MgkX55xfp8E40UptnG6AI+ix1feW/mQZb4JWmc9vJOdcekNzpdVHdYuji/7OhHHofqeoex+M/NUtpv1qpzQfiAz8f96jfpPRnhLLDkF/mwBvbC0TMGaFXw45kkpBdpzvNLkFDt1DoSmdcrd7c7VP/sBDGpMaBWnbgUm2SdhICKEnlH5CrWWx3TyNdWPR1UiNsf9JIiP4AB1Q0Fxpkp1QLH5CXdtCQDTxNHhokjz2Hh6K8lyvXucDjgyll9qRVNZNlllRk6ckDD2W0xnl15+okmcNx3J9dk/vZjM2BLoIr7lzCadUS/EiEnNHbbOXzHUWI3TFG7xXgd/00t7bKid3wYeg0zNrg1+x5XHtbnsjkmgHLoUjpV78WQcWqoZ5Qp3E7O+Q3gepkE9gEtgnoGkzu6nh/1j341VceqH1emUaNzY9E7kmWJObx5ck+dFSf2S0KkxXT3lCkYh485g1sg8dcO0tv1PLnkJK+yEYQbGWWZheoHbyY440cD2c3udPDqwvHLpoYxiGumtODFRzdop30J+002T/rHzpHj7q+VpL7v5Ea0aB2std4rURQQx/ZCL1vgW+1OGM36JzcI+eidzIOTo5DClsCwZxaiTqShJzSEuw45W9IKRe52EXuXWm/yIOjWLuNDMkKavmZUmcIrDcSia8drIYmxDhh6t7YSDo1WRFvny2RiiuTm90mEh+krIAeWg==
  template:
    metadata:
      name: redis-auth
      namespace: database
