apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: samba-storage
  namespace: samba
  labels:
    app: samba
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Gi
