apiVersion: v1
kind: PersistentVolume
metadata:
  name: samba-storage
  labels:
    app: samba
spec:
  capacity:
    storage: 100Gi  # Adjust based on your server's available space
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /mnt/samba-share  # Directory on the k3s host node
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: Exists
